baseURL = 'https://topjer.net/'
languageCode = 'en-us'
title = 'topjer.net'
theme = 'papermod'
enableRobotsTXT = true
mainsections = ["posts", "papermod"]
pygmentsUseClasses = true

[params]
author = "Topjer"
title = "Foo"
description = "This is a test"
defaultTheme = "dark"
showReadingTime = true
showShareButtons = false
showPostNavLinks = true
useHugoToc = true
showToc = true
showPageNums = true
tocopen = false
ShowBreadCrumps = true
hideSummary = false

[[params.socialIcons]]
name = "github"
url = "https://github.com/topjer"

[[params.socialIcons]]
name = "medium"
url = "https://medium.com/@christopher-schmaeche"

[[params.socialIcons]]
name = "other"
url = "https://topjer.substack.com/"
title = "My Substack"

[params.homeInfoParams]
Title = "Code Learn Grow"
Content = "Enjoy digging through articles I have written in the past."

[profileMode]
enabled = true
title = "Foo"
subtitle = "Bar"
buttons = { name = "Posts", url = "posts" }

[menu]
main = [
    #{identifier = "categories", name = "categories"},
    { identifier = "tags", name = "tags", url = "/tags/" },
]
