baseURL = 'https://topjer.net/'
languageCode = 'en-us'
title = 'topjer.net'
theme = 'papermod'
enableRobotsTXT = true
mainsections = ["posts", "papermod"]
pygmentsUseClasses = true

[params]
author = "Topjer"
title = "Foo"
description = "This is a test"
defaultTheme = "dark"
showReadingTime = true
showShareButtons = false
showPostNavLinks = true
useHugoToc = true
showToc = false
showPageNums = true
tocopen = false
ShowBreadCrumps = true
hideSummary = false
socialIcons = [{ name = "github", url = "https://github.com/topjer" }]

[params.homeInfoParams]
Title = ""
Content = "Enjoy digging through articles I have written in the past."

[profileMode]
enabled = true
title = "Foo"
subtitle = "Bar"
buttons = { name = "Posts", url = "posts" }

[menu]
main = [
    #{identifier = "categories", name = "categories"},
    { identifier = "tags", name = "tags", url = "/tags/" },
]
